Repository IBM/ibm-elastic-stack-operator, pull requests merged in 2020-04, with the labels that each got.

#9 For issue identified in #35774 (IBMPrivateCloud/roadmap#35774)
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: lgtm, ok-to-test, size/XS

#11 Update README.md
  README.md
Labels: approved, lgtm, ok-to-test, size/S

#10 switch to new csv version, fixes 36553 metering annotation
  .osdk-scorecard.yaml
  Makefile
  commonUtil/scripts/push-csv.sh
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.1/elasticstack.ibm.com_elasticstacks_crd.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.1/ibm-elastic-stack-operator.v3.1.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/ibm-elastic-stack-operator.package.yaml
  deploy/operator.yaml
  helm-charts/ibm-icplogging/Chart.yaml
  helm-charts/ibm-icplogging/README.md
  helm-charts/ibm-icplogging/templates/es-data-statefulset.yaml
  helm-charts/ibm-icplogging/templates/kibana-deployment.yaml
  helm-charts/ibm-icplogging/templates/ls-deployment.yaml
  helm-charts/ibm-icplogging/values-metadata.yaml
  version/version.go
Labels: approved, lgtm, size/XXL

#13 Add namespace selector of netowrkpolicy to support VA case
  helm-charts/ibm-icplogging/templates/es-data-netpol.yaml
Labels: approved, lgtm, size/XS
