Repository IBM/ibm-elastic-stack-operator, pull requests merged in 2020-09, with the labels that each got.

#56 Enabling Operator for multiple architectures and operating systems
  deploy/crds/elasticstack.ibm.com_elasticstacks_crd.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.0.5/elasticstack.ibm.com_elasticstacks_crd.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.1/elasticstack.ibm.com_elasticstacks_crd.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.2/elasticstack.ibm.com_elasticstacks_crd.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.3/elasticstack.ibm.com_elasticstacks_crd.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.4/elasticstack.ibm.com_elasticstacks_crd.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.2.0/elasticstack.ibm.com_elasticstacks_crd.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.2.0/ibm-elastic-stack-operator.v3.2.0.clusterserviceversion.yaml
Labels: approved, size/S

#59 fixed sevice selectors
  deploy/sample-crs/dev.yaml
  helm-charts/ibm-icplogging/templates/es-data-service.yaml
  helm-charts/ibm-icplogging/templates/es-discovery-service.yaml
  helm-charts/ibm-icplogging/templates/kibana-service.yaml
  helm-charts/ibm-icplogging/templates/ls-service.yaml
Labels: approved, size/M

#63 update management ingress image digest
  deploy/crds/elasticstack.ibm.com_v1alpha1_elasticstack_cr.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/ibm-elastic-stack-operator.package.yaml
  helm-charts/ibm-icplogging/values.yaml
  version/version.go
Labels: approved, size/S

#64 update digests for canary build fail
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.5/elasticstack.ibm.com_elasticstacks_crd.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.5/ibm-elastic-stack-operator.v3.1.5.clusterserviceversion.yaml
  helm-charts/ibm-icplogging/values.yaml
Labels: approved, size/XXL

#66 fixes 40141 on amd
  Makefile
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/entrypoint.sh
  build/upgrade-cr.sh
  deploy/olm-catalog/ibm-elastic-stack-operator/3.2.2/ibm-elastic-stack-operator.v3.2.2.clusterserviceversion.yaml
  deploy/operator.yaml
  deploy/sample-crs/dev.yaml
  helm-charts/ibm-icplogging/templates/_helpers.tpl
Labels: approved, size/L

#67 fixes 40141 - s390x changes
  build/Dockerfile.s390x
Labels: approved, needs-ok-to-test, size/S

#68 Elk uplift 37018
  deploy/sample-crs/dev.yaml
  helm-charts/ibm-icplogging/values.yaml
Labels: approved, size/M

#71 fix multiarch image build.
  Makefile
  commonUtil/Makefile.common.mk
  commonUtil/scripts/install-operator-sdk.sh
  commonUtil/scripts/multiarch_image.sh
Labels: size/L

#69 ported operator image to ppc
  build/Dockerfile
  build/Dockerfile.ppc64le
Labels: approved, size/S

#73 fix build push failures and 41460
  Makefile
  build/upgrade-cr.sh
  commonUtil/scripts/config_docker.sh
Labels: approved, size/S

#65 3.5.4 linting
  deploy/crds/elasticstack.ibm.com_v1alpha1_elasticstack_cr.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.5/elasticstack.ibm.com_elasticstacks_crd.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.2.0/elasticstack.ibm.com_elasticstacks_crd.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.2.0/ibm-elastic-stack-operator.v3.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.2.2/elasticstack.ibm.com_elasticstacks_crd.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.2.2/ibm-elastic-stack-operator.v3.2.2.clusterserviceversion.yaml
  deploy/service_account.yaml
  helm-charts/ibm-icplogging/RELEASENOTES.md
  helm-charts/ibm-icplogging/templates/_helpers.tpl
  helm-charts/ibm-icplogging/templates/kibana-migration-job.yaml
Labels: size/M

#74 switched yq to 3.3
  build/Dockerfile.s390x
Labels: approved, size/XS
