Repository IBM/ibm-elastic-stack-operator, pull requests merged in 2020-11, with the labels that each got.

#78 Uninstall 42090
  .osdk-scorecard.yaml
  Makefile
  README.md
  build/upgrade-cr.sh
  deploy/olm-catalog/ibm-elastic-stack-operator/3.2.4/elasticstack.ibm.com_elasticstacks_crd.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.2.4/ibm-elastic-stack-operator.v3.2.4.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/ibm-elastic-stack-operator.package.yaml
  helm-charts/ibm-icplogging/Chart.yaml
  version/version.go
Labels: approved, lgtm, size/XXL

#80 update management ingress image to resolve container loop backoff issue
  helm-charts/ibm-icplogging/values.yaml
Labels: lgtm, size/XS

#81 fixes operator startup failures, upgraded base image
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  build/upgrade-cr.sh
Labels: approved, size/S
