Repository IBM/ibm-elastic-stack-operator, pull requests merged in 2020-03, with the labels that each got.

#3 fixes 35457, 36251, 36496 metering annotation for logging
  deploy/olm-catalog/ibm-elastic-stack-operator/0.0.1/ibm-elastic-stack-operator.v0.0.1.clusterserviceversion.yaml
  helm-charts/ibm-icplogging/templates/es-curator-cronjob.yaml
  helm-charts/ibm-icplogging/templates/es-data-statefulset.yaml
  helm-charts/ibm-icplogging/templates/es-pki-delete-job.yaml
  helm-charts/ibm-icplogging/templates/es-pki-init-job.yaml
  helm-charts/ibm-icplogging/templates/fb-ds.yaml
  helm-charts/ibm-icplogging/templates/kibana-deployment.yaml
  helm-charts/ibm-icplogging/templates/kibana-init-job.yaml
  helm-charts/ibm-icplogging/templates/ls-deployment.yaml
  version/version.go
Labels: approved, lgtm, size/L

#4 lint
  Makefile
Labels: approved, size/XS

#5 removed kube-system reference, updated version, metering annotation
  .osdk-scorecard.yaml
  Makefile
  deploy/crds/elasticstack.ibm.com_v1alpha1_elasticstack_cr.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.0.5/elasticstack.ibm.com_elasticstacks_crd.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.0.5/ibm-elastic-stack-operator.v3.0.5.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/ibm-elastic-stack-operator.package.yaml
  deploy/operator.yaml
  deploy/sample-crs/managed-stack.yaml
  deploy/sample-crs/minimal-stack.yaml
  deploy/sample-crs/tenant-a.sample.yaml
  helm-charts/ibm-icplogging/cv-tests/lintOverrides.yaml
  helm-charts/ibm-icplogging/cv-tests/test-01/application-test/runTests.sh
  helm-charts/ibm-icplogging/cv-tests/test-01/clean-up.sh
  helm-charts/ibm-icplogging/cv-tests/test-01/post-install/post-install.sh
  helm-charts/ibm-icplogging/cv-tests/test-01/pre-install/pre-install.sh
  helm-charts/ibm-icplogging/cv-tests/test-01/pre-install/values-template.yaml
  helm-charts/ibm-icplogging/cv-tests/test-01/values.yaml
  helm-charts/ibm-icplogging/es-client-router/qparser.lua
  helm-charts/ibm-icplogging/es-client-router/rbac.lua
  helm-charts/ibm-icplogging/kibana-init/entrypoint.sh
  helm-charts/ibm-icplogging/kibana-router/nginx.conf
  helm-charts/ibm-icplogging/logstash/k8s.conf
  helm-charts/ibm-icplogging/router-scripts/pim.lua
  helm-charts/ibm-icplogging/router-scripts/pip.lua
  helm-charts/ibm-icplogging/templates/_helpers.tpl
  helm-charts/ibm-icplogging/templates/es-data-statefulset.yaml
  helm-charts/ibm-icplogging/templates/fb-ds.yaml
  helm-charts/ibm-icplogging/templates/kibana-deployment.yaml
  helm-charts/ibm-icplogging/templates/ls-deployment.yaml
  helm-charts/ibm-icplogging/values.icp.yaml
  helm-charts/ibm-icplogging/values.multitenancy.sample.yaml
  helm-charts/ibm-icplogging/values.ocp.dev.yaml
  helm-charts/ibm-icplogging/values.ocp.yaml
  helm-charts/ibm-icplogging/values.yaml
  version/version.go
Labels: approved, size/XL

#6 security constraint and image version 36531, 36711
  Makefile
  deploy/olm-catalog/ibm-elastic-stack-operator/3.0.5/ibm-elastic-stack-operator.v3.0.5.clusterserviceversion.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/sample-crs/managed-stack.scc.yaml
  helm-charts/ibm-icplogging/templates/all-scc.yaml
  helm-charts/ibm-icplogging/templates/es-data-statefulset.yaml
Labels: approved, lgtm, size/L

#7 make kibana UI work
  helm-charts/ibm-icplogging/templates/kibana-deployment.yaml
Labels: approved, lgtm, size/XS

#8 use default storage class for dynamic provisioning
  deploy/crds/elasticstack.ibm.com_v1alpha1_elasticstack_cr.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.0.5/ibm-elastic-stack-operator.v3.0.5.clusterserviceversion.yaml
  helm-charts/ibm-icplogging/templates/es-data-statefulset.yaml
Labels: approved, size/XS
