Repository IBM/ibm-elastic-stack-operator, pull requests merged in 2020-06, with the labels that each got.

#35 switched to 3.1.3
  .osdk-scorecard.yaml
  Makefile
  README.md
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.3/elasticstack.ibm.com_elasticstacks_crd.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.3/ibm-elastic-stack-operator.v3.1.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/ibm-elastic-stack-operator.package.yaml
  helm-charts/ibm-icplogging/Chart.yaml
  helm-charts/ibm-icplogging/ibm_cloud_pak/manifest.yaml
  version/version.go
Labels: approved, size/XXL

#36 increased disk and memory requirement 38409, 38408
  Makefile
  deploy/crds/elasticstack.ibm.com_v1alpha1_elasticstack_cr.yaml
  helm-charts/ibm-icplogging/README.md
  helm-charts/ibm-icplogging/values.icp.yaml
  helm-charts/ibm-icplogging/values.multitenancy.sample.yaml
  helm-charts/ibm-icplogging/values.yaml
Labels: approved, size/S

#37 used force option for future upgrade, longer retry limit for kibana init 38453, 38246
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.3/ibm-elastic-stack-operator.v3.1.3.clusterserviceversion.yaml
  deploy/role.yaml
  helm-charts/ibm-icplogging/templates/kibana-init-job.yaml
Labels: approved, size/XS

#39 switch 313 to beta
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.3/ibm-elastic-stack-operator.v3.1.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/ibm-elastic-stack-operator.package.yaml
Labels: approved, size/XS

#41 move 313 to stable
  deploy/olm-catalog/ibm-elastic-stack-operator/ibm-elastic-stack-operator.package.yaml
Labels: approved, size/XS

#43 switched to 3.1.4
  .osdk-scorecard.yaml
  Makefile
  README.md
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.4/elasticstack.ibm.com_elasticstacks_crd.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.4/ibm-elastic-stack-operator.v3.1.4.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/ibm-elastic-stack-operator.package.yaml
  helm-charts/ibm-icplogging/Chart.yaml
  helm-charts/ibm-icplogging/ibm_cloud_pak/manifest.yaml
  helm-charts/ibm-icplogging/values.yaml
  version/version.go
Labels: approved, size/XXL

#44 push 3.1.4 to beta
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.4/ibm-elastic-stack-operator.v3.1.4.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/ibm-elastic-stack-operator.package.yaml
Labels: approved, size/XS

#46 switched dev to 3.2.0
  .osdk-scorecard.yaml
  Makefile
  README.md
  deploy/olm-catalog/ibm-elastic-stack-operator/3.2.0/elasticstack.ibm.com_elasticstacks_crd.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.2.0/ibm-elastic-stack-operator.v3.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/ibm-elastic-stack-operator.package.yaml
  helm-charts/ibm-icplogging/Chart.yaml
  helm-charts/ibm-icplogging/ibm_cloud_pak/manifest.yaml
  version/version.go
Labels: approved, size/XXL

#48 pushed 3.1.4 to stable-v1
  deploy/olm-catalog/ibm-elastic-stack-operator/ibm-elastic-stack-operator.package.yaml
Labels: approved, size/XS

#45 Fix license documentation in deploy & helm-charts dir
  deploy/crds/elasticstack.ibm.com_elasticstacks_crd.yaml
  deploy/crds/elasticstack.ibm.com_v1alpha1_elasticstack_cr.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.0.5/elasticstack.ibm.com_elasticstacks_crd.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.0.5/ibm-elastic-stack-operator.v3.0.5.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.1/elasticstack.ibm.com_elasticstacks_crd.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.1/ibm-elastic-stack-operator.v3.1.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.2/elasticstack.ibm.com_elasticstacks_crd.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.2/ibm-elastic-stack-operator.v3.1.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.3/elasticstack.ibm.com_elasticstacks_crd.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.3/ibm-elastic-stack-operator.v3.1.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.4/elasticstack.ibm.com_elasticstacks_crd.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.4/ibm-elastic-stack-operator.v3.1.4.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/ibm-elastic-stack-operator.package.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/sample-crs/managed-stack.scc.yaml
  deploy/sample-crs/managed-stack.yaml
  deploy/sample-crs/minimal-stack.yaml
  deploy/sample-crs/tenant-a.sample.yaml
  deploy/sample-crs/tenant-a.scc.yaml
  deploy/service_account.yaml
  helm-charts/ibm-icplogging/elasticsearch/general.config
  helm-charts/ibm-icplogging/es-client-router/nginx.conf
  helm-charts/ibm-icplogging/es-client-router/qparser.lua
  helm-charts/ibm-icplogging/es-client-router/rbac.lua
  helm-charts/ibm-icplogging/es-migration/migrate-elk551-data.sh
  helm-charts/ibm-icplogging/filebeat/filebeat.yml
  helm-charts/ibm-icplogging/filebeat/k8s.yml
  helm-charts/ibm-icplogging/ibm_cloud_pak/manifest.yaml
  helm-charts/ibm-icplogging/kibana-init/entrypoint.sh
  helm-charts/ibm-icplogging/kibana-migration-check/check-migration.sh
  helm-charts/ibm-icplogging/kibana-migration/migrate.sh
  helm-charts/ibm-icplogging/kibana-router/nginx.conf
  helm-charts/ibm-icplogging/kibana/kibana.yml
  helm-charts/ibm-icplogging/templates/_helpers.tpl
  helm-charts/ibm-icplogging/templates/_version.tpl
  helm-charts/ibm-icplogging/templates/es-data-netpol.yaml
  helm-charts/ibm-icplogging/templates/es-sa.yaml
  helm-charts/ibm-icplogging/templates/fb-input-config.yaml
  helm-charts/ibm-icplogging/templates/fb-sa.yaml
  helm-charts/ibm-icplogging/templates/job-sa.yaml
  helm-charts/ibm-icplogging/templates/kibana-migration-check-config.yaml
  helm-charts/ibm-icplogging/templates/kibana-sa.yaml
  helm-charts/ibm-icplogging/templates/ls-sa.yaml
Labels: approved, needs-ok-to-test, size/XL

#47 Updated license headers in commonUtil, deploy, helm-charts dir
  .osdk-scorecard.yaml
  commonUtil/resources/opencloud-operators.yaml
  deploy/scripts/deploy_managed.sh
  deploy/scripts/deploy_operator.sh
  deploy/scripts/deploy_tenant.sh
  deploy/scripts/prepare_tools.sh
  deploy/scripts/undeploy_managed.sh
  deploy/scripts/undeploy_operator.sh
  deploy/scripts/undeploy_tenant.sh
  helm-charts/ibm-icplogging/logstash/jvm.options
  helm-charts/ibm-icplogging/logstash/k8s.conf
  helm-charts/ibm-icplogging/logstash/log4j2.properties
  helm-charts/ibm-icplogging/logstash/logstash.yml
  helm-charts/ibm-icplogging/logstash/startup.options
  helm-charts/ibm-icplogging/preinstall/pv-data-class.yaml
  helm-charts/ibm-icplogging/preinstall/pv-data-none.yaml
  helm-charts/ibm-icplogging/preinstall/pv-data-selector.yaml
  helm-charts/ibm-icplogging/router-scripts/kibanarouter.lua
  helm-charts/ibm-icplogging/router-scripts/pdp.lua
  helm-charts/ibm-icplogging/router-scripts/pim.lua
  helm-charts/ibm-icplogging/router-scripts/pip.lua
  helm-charts/ibm-icplogging/router-scripts/set.lua
  helm-charts/ibm-icplogging/router-scripts/util.lua
  helm-charts/ibm-icplogging/values.ocp.yaml
  helm-charts/ibm-icplogging/values/calculated-values.yml
  helm-charts/ibm-icplogging/values/user-values.yml
  helm-charts/ibm-icplogging/xpack/role_mapping.yml
  helm-charts/ibm-icplogging/xpack/roles.yml
  watches.yaml
Labels: approved, needs-ok-to-test, size/L

#49 [wip] 37302 helm chart changes for uplifting
  helm-charts/ibm-icplogging/es-migration/migrate-elk551-data.sh
  helm-charts/ibm-icplogging/kibana-init/entrypoint.sh
  helm-charts/ibm-icplogging/kibana-migration-check/check-migration.sh
  helm-charts/ibm-icplogging/kibana-migration/migrate.sh
  helm-charts/ibm-icplogging/templates/_helpers.tpl
  helm-charts/ibm-icplogging/values.6.8.10.yaml
Labels: approved, do-not-merge/work-in-progress, size/M
