Repository IBM/ibm-elastic-stack-operator, pull requests merged in 2020-05, with the labels that each got.

#16 added dependency info fixes 36969
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.1/ibm-elastic-stack-operator.v3.1.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#17 resolves scc conflict 37893
  deploy/sample-crs/managed-stack.scc.yaml
  helm-charts/ibm-icplogging/templates/es-scc.yaml
  helm-charts/ibm-icplogging/templates/fb-scc.yaml
  helm-charts/ibm-icplogging/templates/job-scc.yaml
  helm-charts/ibm-icplogging/templates/kbiana-scc.yaml
  helm-charts/ibm-icplogging/templates/ls-scc.yaml
Labels: approved, lgtm, size/S

#18 fixes auth exception for non cluster admin user 37848
  helm-charts/ibm-icplogging/es-client-router/nginx.conf
  helm-charts/ibm-icplogging/es-client-router/qparser.lua
  helm-charts/ibm-icplogging/es-client-router/rbac.lua
  helm-charts/ibm-icplogging/router-scripts/pim.lua
Labels: approved, lgtm, size/L

#19 refreshed image tags for cs 3.4 release
  deploy/crds/elasticstack.ibm.com_v1alpha1_elasticstack_cr.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.1/ibm-elastic-stack-operator.v3.1.1.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/ibm-icplogging/README.md
  helm-charts/ibm-icplogging/templates/es-curator-cronjob.yaml
  helm-charts/ibm-icplogging/templates/es-data-statefulset.yaml
  helm-charts/ibm-icplogging/templates/es-pki-delete-job.yaml
  helm-charts/ibm-icplogging/templates/es-pki-init-job.yaml
  helm-charts/ibm-icplogging/templates/fb-ds.yaml
  helm-charts/ibm-icplogging/templates/kibana-deployment.yaml
  helm-charts/ibm-icplogging/templates/kibana-init-job.yaml
  helm-charts/ibm-icplogging/templates/ls-deployment.yaml
  helm-charts/ibm-icplogging/values.yaml
Labels: approved, size/M

#20 move csv to beta 38053
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.1/ibm-elastic-stack-operator.v3.1.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/ibm-elastic-stack-operator.package.yaml
  deploy/operator.yaml
Labels: approved, size/S

#21 switched to 312 dev channel
  .osdk-scorecard.yaml
  Makefile
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.2/elasticstack.ibm.com_elasticstacks_crd.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.2/ibm-elastic-stack-operator.v3.1.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/ibm-elastic-stack-operator.package.yaml
  deploy/operator.yaml
  helm-charts/ibm-icplogging/Chart.yaml
  version/version.go
Labels: approved

#22 switched operands to digest fixes 37385
  helm-charts/ibm-icplogging/templates/_helpers.tpl
  helm-charts/ibm-icplogging/templates/es-curator-cronjob.yaml
  helm-charts/ibm-icplogging/templates/es-data-statefulset.yaml
  helm-charts/ibm-icplogging/templates/es-pki-delete-job.yaml
  helm-charts/ibm-icplogging/templates/es-pki-init-job.yaml
  helm-charts/ibm-icplogging/templates/fb-ds.yaml
  helm-charts/ibm-icplogging/templates/kibana-deployment.yaml
  helm-charts/ibm-icplogging/templates/kibana-init-job.yaml
  helm-charts/ibm-icplogging/templates/ls-deployment.yaml
  helm-charts/ibm-icplogging/values.yaml
Labels: approved, size/M

#23 csv switched operands to digest fixes 37385
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.1/ibm-elastic-stack-operator.v3.1.1.clusterserviceversion.yaml
Labels: approved, size/XS

#24 correct operator image digest
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.1/ibm-elastic-stack-operator.v3.1.1.clusterserviceversion.yaml
Labels: approved, size/XS

#26 initial changes for minimum pr
  deploy/crds/elasticstack.ibm.com_elasticstacks_crd.yaml
  deploy/crds/elasticstack.ibm.com_v1alpha1_elasticstack_cr.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.2/elasticstack.ibm.com_elasticstacks_crd.yaml
  helm-charts/ibm-icplogging/ibm_cloud_pak/manifest.yaml
Labels: approved, size/XXL

#27 fixes 38239
  deploy/crds/elasticstack.ibm.com_elasticstacks_crd.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.2/elasticstack.ibm.com_elasticstacks_crd.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.2/ibm-elastic-stack-operator.v3.1.2.clusterserviceversion.yaml
  deploy/sample-crs/managed-stack.yaml
  helm-charts/ibm-icplogging/values.managed.yaml
  helm-charts/ibm-icplogging/values.ocp.yaml
  helm-charts/ibm-icplogging/values.yaml
Labels: approved, size/L

#28 enable force upgrade 37108
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.2/ibm-elastic-stack-operator.v3.1.2.clusterserviceversion.yaml
Labels: approved, size/S

#29 logging operator resource limit fixes 38246
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.2/ibm-elastic-stack-operator.v3.1.2.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/S

#30 avoid helm release upgrades when there is no cr change 38287
  helm-charts/ibm-icplogging/templates/es-pki-delete-job.yaml
  helm-charts/ibm-icplogging/templates/kibana-router-secret.yaml
Labels: approved, size/XS

#31 resource cleanup 38332
  helm-charts/ibm-icplogging/templates/es-pki-delete-job.yaml
Labels: approved, size/XS

#32 updated ver
  README.md
Labels: approved

#33 ver
  README.md
Labels: approved

#34 moving logging to beta channel 38349
  deploy/olm-catalog/ibm-elastic-stack-operator/3.1.2/ibm-elastic-stack-operator.v3.1.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-elastic-stack-operator/ibm-elastic-stack-operator.package.yaml
  deploy/operator.yaml
Labels: approved, size/S
